### ISSUE TITLE
xcode 8 isn't a dmg file

### ISSUE THREAD

**Issue by oryagel** [madelaney/puppet-xcode#3]
Hi,
Apple changed the installation file on xcode 8. Now it's xip file instead of dmg.
Is there a way to install it using this module?

Thanks

**Comment by steveames** [comment]
Thank you for this! XIP support would be very welcome. If you need someone to test... I run about every combination of OSX/MacOS and XCode. Not having to convert the .xip to a local .dmg would save me some periodic effort.

**Comment by madelaney** [comment]
With version 1.0.x, this now supports XIP files. I've been testing for a bit and things seem solid. Sorry for the massive delay in getting this out.
